import { FamilyNameVersion, VersionInfo } from "@/lib/family-name-picker/types";

export const familyNames = [
  "김기훈",
  "김수진",
  "김나린",
  "김나율",
  "김나준",
  "김종구",
  "김민정",
  "김영진",
  "서경미",
  "김정환",
  "최은서",
  "김민주",
  "최문석",
  "최지웅",
  "김예지",
  "조성길",
  "조은하",
  "조은비",
] as const;

export const distractorNames = [
  "김도윤",
  "김도현",
  "김서연",
  "김서준",
  "김하율",
  "김예린",
  "박지우",
  "박서준",
  "박서연",
  "박하준",
  "박지민",
  "이도윤",
  "이서준",
  "이서연",
  "이지우",
  "이하린",
  "최서윤",
  "최하준",
  "최지후",
  "최민준",
  "정하윤",
  "정지호",
  "정예은",
  "정민준",
  "서하윤",
  "서준우",
  "서예린",
  "서지안",
  "조하린",
  "조민준",
  "조서윤",
  "조지후",
  "윤서진",
  "윤지호",
  "윤예나",
  "한서준",
  "한지우",
  "한예린",
  "오지후",
  "오하윤",
] as const;

export const versionInfo: Record<FamilyNameVersion, VersionInfo> = {
  nayul: {
    label: "나율이 버전",
    shortLabel: "나율이",
    difficultyLabel: "쉬운 버전",
    accentClassName: "from-rose-400 via-pink-400 to-orange-300",
    accentButtonClassName: "bg-rose-500 hover:bg-rose-600",
    softPanelClassName: "from-rose-50 via-pink-50 to-orange-50",
    summary: "지금 방식 그대로, 보기 5개 중에서 우리 가족 이름 하나를 천천히 찾아 눌러요.",
    example: "보기 5개 · 시간 제한 없음",
    choiceCount: 5,
  },
  narin: {
    label: "나린이 버전",
    shortLabel: "나린이",
    difficultyLabel: "도전 버전",
    accentClassName: "from-sky-400 via-cyan-400 to-indigo-400",
    accentButtonClassName: "bg-sky-500 hover:bg-sky-600",
    softPanelClassName: "from-sky-50 via-cyan-50 to-indigo-50",
    summary: "보기 7개 속에서 10초 안에 가족 이름을 찾아야 하는 빠른 도전 버전이에요.",
    example: "보기 7개 · 10초 제한",
    choiceCount: 7,
    timeLimitSeconds: 10,
  },
};
